scalar Link
scalar Token
scalar Upload

union AnyType = User

type Response {
    status: Int!
    message: String!
    data: AnyType
}

type AuthResponse {
    status: Int!
    message: String!
    token: Token
    data: AnyType
}